/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var mpilot = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,4],$V1=[1,9],$V2=[5,7],$V3=[1,14],$V4=[1,22],$V5=[1,28],$V6=[1,29],$V7=[1,30],$V8=[1,31],$V9=[1,32],$Va=[12,14],$Vb=[12,14,27],$Vc=[2,20],$Vd=[2,21],$Ve=[7,12,14,17,18,27],$Vf=[1,45],$Vg=[1,46],$Vh=[1,48],$Vi=[1,49],$Vj=[14,27],$Vk=[2,43],$Vl=[1,56],$Vm=[1,55],$Vn=[1,59],$Vo=[1,67];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"program":3,"commands":4,"EOF":5,"command":6,"ID":7,"EQUAL":8,"arguments":9,"LPAREN":10,"argument_list":11,"RPAREN":12,"argument":13,"COMMA":14,"expression":15,"plain_expression":16,"COLON":17,"PLAIN_STRING":18,"number":19,"STRING":20,"list":21,"boolean":22,"INT":23,"FLOAT":24,"LBRACK":25,"elements":26,"RBRACK":27,"element":28,"tuple_pairs":29,"plain_tuple_expression":30,"tuple_pair":31,"ELEMENT_PLAIN_STRING":32,"TRUE":33,"FALSE":34,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",7:"ID",8:"EQUAL",10:"LPAREN",12:"RPAREN",14:"COMMA",17:"COLON",18:"PLAIN_STRING",20:"STRING",23:"INT",24:"FLOAT",25:"LBRACK",27:"RBRACK",32:"ELEMENT_PLAIN_STRING",33:"TRUE",34:"FALSE"},
productions_: [0,[3,2],[4,2],[4,1],[6,4],[6,2],[9,3],[9,2],[11,3],[11,2],[11,1],[13,3],[13,3],[16,1],[16,3],[16,1],[16,2],[16,3],[16,2],[16,2],[15,1],[15,1],[15,1],[15,1],[19,1],[19,1],[21,3],[21,2],[26,3],[26,2],[26,1],[26,1],[28,1],[28,1],[29,3],[29,2],[29,1],[31,3],[31,3],[31,3],[31,3],[31,3],[31,3],[30,1],[30,1],[30,2],[30,2],[30,2],[22,1],[22,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
return {commands: $$[$0-1], version: yy.parser.EEMSv2 ? 2 : 3};
break;
case 2:
this.$ = [].concat([$$[$0-1]], $$[$0]);
break;
case 3: case 10: case 30:
this.$ = [$$[$0]];
break;
case 4:
this.$ = {resultName: $$[$0-3], command: $$[$0-1], arguments: $$[$0], lineno: this._$.first_line};
break;
case 5:
yy.parser.EEMSv2 = true; this.$ = {resultName: null, command: $$[$0-1], arguments: $$[$0], lineno: this._$.first_line};
break;
case 6: case 26: case 35:
this.$ = $$[$0-1];
break;
case 7: case 27:
this.$ = [];
break;
case 8: case 28:
this.$ = [].concat([$$[$0-2]], $$[$0]);
break;
case 9: case 29:
this.$ = [$$[$0-1]];
break;
case 11: case 12:
this.$ = {name: $$[$0-2], value: $$[$0], lineno: this._$.first_line};
break;
case 13: case 43:
this.$ = {value: yytext, lineno: this._$.first_line};
break;
case 14:
this.$ = {value: $$[$0-2] + $$[$0-1] + parseEntities($$[$0]), lineno: this._$.first_line};
break;
case 15: case 44:
this.$ = {value: parseEntities(yytext), lineno: this._$.first_line};
break;
case 16: case 45:
this.$ = {value: $$[$0-1] + parseEntities($$[$0]), lineno: this._$.first_line};
break;
case 17:
this.$ = {value: '' + $$[$0-2] + $$[$0-1] + parseEntities($$[$0]), lineno: this._$.first_line};
break;
case 18: case 46:
this.$ = {value: '' + $$[$0-1] + parseEntities($$[$0]), lineno: this._$.first_line};
break;
case 19: case 47:
this.$ = {value: '' + $$[$0-1] + $$[$0], lineno: this._$.first_line};
break;
case 20:
this.$ = {value: parseEntities(yytext.substr(1, yytext.length-2)), lineno: this._$.first_line};
break;
case 21: case 22: case 23:
this.$ = {value: $$[$0], lineno: this._$.first_line};
break;
case 24:
this.$ = Number.parseInt(yytext);
break;
case 25:
this.$ = Number.parseFloat(yytext);
break;
case 31: case 32: case 33: case 36:
this.$ = $$[$0];
break;
case 34:
this.$ = Object.assign({}, $$[$0], $$[$0-2]);
break;
case 37: case 40:
this.$ = {[$$[$0-2].substr(1, $$[$0-2].length-2)]: $$[$0]};
break;
case 38: case 39: case 41: case 42:
this.$ = {[$$[$0-2]]: $$[$0]};
break;
case 48:
this.$ = true;
break;
case 49:
this.$ = false;
break;
}
},
table: [{3:1,4:2,6:3,7:$V0},{1:[3]},{5:[1,5]},{4:6,5:[2,3],6:3,7:$V0},{8:[1,7],9:8,10:$V1},{1:[2,1]},{5:[2,2]},{7:[1,10]},o($V2,[2,5]),{7:$V3,11:11,12:[1,12],13:13},{9:15,10:$V1},{12:[1,16]},o($V2,[2,7]),{12:[2,10],14:[1,17]},{8:[1,18]},o($V2,[2,4]),o($V2,[2,6]),{7:$V3,11:19,12:[2,9],13:13},{7:[1,26],15:20,16:21,18:[1,27],19:23,20:$V4,21:24,22:25,23:$V5,24:$V6,25:$V7,33:$V8,34:$V9},{12:[2,8]},o($Va,[2,11]),o($Va,[2,12]),o($Vb,$Vc),o($Va,$Vd,{7:[1,35],17:[1,33],18:[1,34]}),o($Vb,[2,22]),o($Vb,[2,23]),o($Va,[2,13],{17:[1,36],18:[1,37]}),o($Va,[2,15]),o($Ve,[2,24]),o($Ve,[2,25]),{7:$Vf,15:43,18:$Vg,19:47,20:$Vh,21:24,22:25,23:$V5,24:$V6,25:$V7,26:38,27:[1,39],28:40,29:41,30:42,31:44,32:$Vi,33:$V8,34:$V9},o($Vb,[2,48]),o($Vb,[2,49]),{18:[1,50]},o($Va,[2,18]),o($Va,[2,19]),{18:[1,51]},o($Va,[2,16]),{27:[1,52]},o($Vb,[2,27]),{14:[1,53],27:[2,30]},{27:[2,31]},o($Vj,[2,32]),o($Vj,[2,33]),{14:[1,54],27:[2,36]},o($Vj,$Vk,{17:$Vl,18:$Vm}),o($Vj,[2,44]),o($Vj,$Vd,{7:[1,58],18:[1,57]}),o($Vj,$Vc,{17:$Vn}),{17:[1,60]},o($Va,[2,17]),o($Va,[2,14]),o($Vb,[2,26]),{7:$Vf,15:43,18:$Vg,19:47,20:$Vh,21:24,22:25,23:$V5,24:$V6,25:$V7,26:61,27:[2,29],28:40,29:41,30:42,31:44,32:$Vi,33:$V8,34:$V9},{7:[1,64],20:[1,63],27:[2,35],29:62,31:44,32:$Vi},o($Vj,[2,45]),{7:$Vo,15:66,18:$Vg,19:47,20:$V4,21:24,22:25,23:$V5,24:$V6,25:$V7,30:65,33:$V8,34:$V9},o($Vj,[2,46]),o($Vj,[2,47]),{7:$Vo,15:69,18:$Vg,19:47,20:$V4,21:24,22:25,23:$V5,24:$V6,25:$V7,30:68,33:$V8,34:$V9},{7:$Vo,15:71,18:$Vg,19:47,20:$V4,21:24,22:25,23:$V5,24:$V6,25:$V7,30:70,33:$V8,34:$V9},{27:[2,28]},{27:[2,34]},{17:$Vn},{17:$Vl},o($Vj,[2,39]),o($Vj,[2,42]),o($Vj,$Vk,{18:$Vm}),o($Vj,[2,37]),o($Vj,[2,40]),o($Vj,[2,38]),o($Vj,[2,41])],
defaultActions: {5:[2,1],6:[2,2],19:[2,8],41:[2,31],61:[2,28],62:[2,34]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

const { parseEntities } = _entities
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* skip whitespace */
break;
case 1:/* ignore comments */
break;
case 2:return "COLON";
break;
case 3:return "COMMA";
break;
case 4:return "EQUAL";
break;
case 5:return "FALSE";
break;
case 6:return "FLOAT";
break;
case 7:return "ID";
break;
case 8:return "INT";
break;
case 9:return "LBRACK";
break;
case 10:return "LPAREN";
break;
case 11:return "RBRACK";
break;
case 12:return "RPAREN";
break;
case 13:return "STRING";
break;
case 14:return "TRUE";
break;
case 15:return "PLAIN_STRING";
break;
case 16:return "EOF";
break;
}
},
rules: [/^(?:\s+)/,/^(?:#.*)/,/^(?::)/,/^(?:,)/,/^(?:=)/,/^(?:False\b)/,/^(?:[\-\+]?((\d+\.\d*)|(\.\d+))([eE][\+\-]?\d+)?)/,/^(?:[a-zA-Z_][a-zA-Z_0-9]*)/,/^(?:[\-\+]?\d+)/,/^(?:\[)/,/^(?:\()/,/^(?:\])/,/^(?:\))/,/^(?:("(\\.|[^\"\\])*")|('(\\.|[^\'\\])*'))/,/^(?:True\b)/,/^(?:[^0-9][^\#\:\,\=\(\)\[\]\"\'\r\n]+)/,/^(?:$)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = mpilot;
exports.Parser = mpilot.Parser;
exports.parse = function () { return mpilot.parse.apply(mpilot, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}